// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AdjustComponentQuantity(arg1:string,arg2:number):Promise<app.ComponentResponse>;

export function ClearSelectedComponentAsset(arg1:string,arg2:string):Promise<void>;

export function ClearSelectedComponentForRequirement(arg1:string):Promise<void>;

export function CreateComponent(arg1:app.CreateComponentInput):Promise<app.ComponentResponse>;

export function CreateComponentAsset(arg1:app.CreateComponentAssetInput):Promise<app.ComponentAssetResponse>;

export function CreateProject(arg1:app.CreateProjectInput):Promise<app.ProjectResponse>;

export function DeleteComponent(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetCategories():Promise<Array<app.CategoryInfo>>;

export function GetCategoryDefinitions(arg1:string):Promise<Array<app.AttributeDefinitionInfo>>;

export function GetComponent(arg1:string):Promise<app.ComponentResponse>;

export function GetComponentDetail(arg1:string):Promise<app.ComponentDetailResponse>;

export function GetOperatorsForValueType(arg1:string):Promise<Array<app.OperatorInfo>>;

export function GetProject(arg1:string):Promise<app.ProjectResponse>;

export function GetStartupStatus():Promise<app.StartupStatusResponse>;

export function ImportComponentAssetResult(arg1:string,arg2:string,arg3:string):Promise<app.AssetImportResponse>;

export function ListComponentAssets(arg1:string):Promise<Array<app.ComponentAssetResponse>>;

export function ListComponents(arg1:app.ComponentFilterInput):Promise<Array<app.ComponentResponse>>;

export function ListProjects():Promise<Array<app.ProjectResponse>>;

export function ListRecentProjects():Promise<Array<app.RecentProjectResponse>>;

export function PlanProject(arg1:string):Promise<app.ProjectPlanResponse>;

export function ReplaceComponentAttributes(arg1:string,arg2:Array<app.AttributeValueInput>):Promise<void>;

export function ReplaceProjectRequirements(arg1:string,arg2:Array<app.RequirementInput>):Promise<void>;

export function SearchComponentAssets(arg1:string,arg2:string):Promise<app.AssetSearchResponse>;

export function SelectComponentAsset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectComponentForRequirement(arg1:string,arg2:string):Promise<void>;

export function UpdateComponentInventory(arg1:app.UpdateInventoryInput):Promise<app.ComponentResponse>;

export function UpdateComponentMetadata(arg1:app.UpdateMetadataInput):Promise<app.ComponentResponse>;

export function UpdateProjectMetadata(arg1:app.UpdateProjectInput):Promise<app.ProjectResponse>;
