// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustComponentQuantity(arg1, arg2) {
  return window['go']['app']['App']['AdjustComponentQuantity'](arg1, arg2);
}

export function ClearSelectedComponentAsset(arg1, arg2) {
  return window['go']['app']['App']['ClearSelectedComponentAsset'](arg1, arg2);
}

export function ClearSelectedComponentForRequirement(arg1) {
  return window['go']['app']['App']['ClearSelectedComponentForRequirement'](arg1);
}

export function CreateComponent(arg1) {
  return window['go']['app']['App']['CreateComponent'](arg1);
}

export function CreateComponentAsset(arg1) {
  return window['go']['app']['App']['CreateComponentAsset'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function DeleteComponent(arg1) {
  return window['go']['app']['App']['DeleteComponent'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function GetCategories() {
  return window['go']['app']['App']['GetCategories']();
}

export function GetCategoryDefinitions(arg1) {
  return window['go']['app']['App']['GetCategoryDefinitions'](arg1);
}

export function GetComponent(arg1) {
  return window['go']['app']['App']['GetComponent'](arg1);
}

export function GetComponentDetail(arg1) {
  return window['go']['app']['App']['GetComponentDetail'](arg1);
}

export function GetOperatorsForValueType(arg1) {
  return window['go']['app']['App']['GetOperatorsForValueType'](arg1);
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetStartupStatus() {
  return window['go']['app']['App']['GetStartupStatus']();
}

export function ImportComponentAssetResult(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportComponentAssetResult'](arg1, arg2, arg3);
}

export function ListComponentAssets(arg1) {
  return window['go']['app']['App']['ListComponentAssets'](arg1);
}

export function ListComponents(arg1) {
  return window['go']['app']['App']['ListComponents'](arg1);
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListRecentProjects() {
  return window['go']['app']['App']['ListRecentProjects']();
}

export function PlanProject(arg1) {
  return window['go']['app']['App']['PlanProject'](arg1);
}

export function ReplaceComponentAttributes(arg1, arg2) {
  return window['go']['app']['App']['ReplaceComponentAttributes'](arg1, arg2);
}

export function ReplaceProjectRequirements(arg1, arg2) {
  return window['go']['app']['App']['ReplaceProjectRequirements'](arg1, arg2);
}

export function SearchComponentAssets(arg1, arg2) {
  return window['go']['app']['App']['SearchComponentAssets'](arg1, arg2);
}

export function SelectComponentAsset(arg1, arg2, arg3) {
  return window['go']['app']['App']['SelectComponentAsset'](arg1, arg2, arg3);
}

export function SelectComponentForRequirement(arg1, arg2) {
  return window['go']['app']['App']['SelectComponentForRequirement'](arg1, arg2);
}

export function UpdateComponentInventory(arg1) {
  return window['go']['app']['App']['UpdateComponentInventory'](arg1);
}

export function UpdateComponentMetadata(arg1) {
  return window['go']['app']['App']['UpdateComponentMetadata'](arg1);
}

export function UpdateProjectMetadata(arg1) {
  return window['go']['app']['App']['UpdateProjectMetadata'](arg1);
}
